name: Build

on: [push]

env:
  CIBW_SKIP: cp34-* cp35-* *-manylinux_i686 *-win32
  CIBW_BUILD: cp3?-*
  CIBW_BEFORE_BUILD: git submodule update --init --recursive
  CIBW_TEST_COMMAND: python -m pip install Pillow && python {project}/test.py && python {project}/perf.py

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] # 

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.2
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist
    - name: Look
      run: |
        ls dist
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./dist

  build_source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'
    
    - name: Build source
      run: |
        git submodule update --init --recursive
        python -m pip install setuptools wheel Cython>=3.0a4 numpy
        python setup.py sdist --formats=zip
    - name: Look
      run: |
        ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist
  
  upload:
    runs-on: ubuntu-latest
    needs: [build_source, build_wheels]
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: wheels
        path: ./dist
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      continue-on-error: true
      with:
        password: ${{ secrets.testpypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
